### ISSUE TITLE
npm WARN certstreamcatcher@1.0.1 No repository field 

### ISSUE THREAD

**Issue by n13lo** [6IX7ine/certstreamcatcher#1]
Hi all.
How is it done? please
[https://asciinema.org/a/3K8eHqhSQBTq47ZYQksb70MoT](url)

**Comment by jimywork** [comment]
try git clone https://github.com/6IX7ine/certstreamcatcher/
after cloning you enter the folder type **npm install** and then enter the sample folder to run the program.

**Comment by n13lo** [comment]
# thanks for answering.
2017-12-26 12:51:55 ⌚ pericardi in ~/.npm
○ → sudo npm install
[sudo] password for coy:
npm WARN enoent ENOENT: no such file or directory, open '/home/coy/package.json'
npm WARN coy No description
npm WARN coy No repository field.
npm WARN coy No README data
npm WARN coy No license field.

2017-12-26 12:52:08 ⌚ pericardi in ~/.npm
○ → cd /opt/certstreamcatcher/

2017-12-26 12:57:24 ⌚ pericardi in /opt/certstreamcatcher
± |master ✓| → ls
demo.gif example index.js node_modules package.json README.md

2017-12-26 12:57:25 ⌚ pericardi in /opt/certstreamcatcher
± |master ✓| → ### sudo npm install
npm WARN certstreamcatcher@1.0.1 No repository field.

2017-12-26 12:57:34 ⌚ pericardi in /opt/certstreamcatcher
± |master ✓| → ### cd example/

2017-12-26 12:57:47 ⌚ pericardi in /opt/certstreamcatcher/example
± |master ✓| → ### node certstreamcatcher.js
Connection established to certstream! Waiting for messages...
[!] Suspicious login.teofilootoni.mg.gov.br
[!] Likely mbox12.loginfor.com.br667m
⠦ 27117 Certs ⊶ Elapsed time 15.300m

2017-12-26 13:13:22 ⌚ pericardi in /opt/certstreamcatcher/example
± |master ✓| →
